buyer/urls.py
from django.urls import path
from . import views

app_name='buyer'

urlpatterns=[
    path('home/',views.home_page),
    path('product/<slug>/',views.ItemDetailView.as_view(),name='product'),
    path('add-to-cart/<slug>/',views.add_to_cart,name='add-to-cart'),
    path('remove-from-cart/<slug>/',views.remove_from_cart,name='remove-from-cart'),
    path('order-summary/',views.OrderSummaryView.as_view(),name='order-summary'),
    path('remove-from-cart/<slug>/', views.remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', views.remove_single_item_from_cart,name='remove-single-item-from-cart'),
    path('checkout/',views.CheckoutView.as_view(),name='checkout'),
    path('pay/',views.pay,name='pay'),
    path('pay/payment-status/',views.payment_status,name='payment-status'),
    path('profile/',views.profile),
    path('add_product/', views.add_prod, name='addProd'),
    path('pay/payment-status/success',views.payment_status_success,name='payment-status-success'),
    path('pay/payment-status/failure',views.payment_status_failure,name='payment-status-failure'),
    path('search/',views.search,name='search'),
    path('logout/', views.logout_view, name='logout'),
    path('home/upgrade', views.addSeller),
    path('upgrade/', views.addSeller),
    path('admin-home/', views.admin_view,name='admin-home'),
    path('reset-account/<slug>/',views.reset_account,name='reset-account'),
    path('open-pdf/pdf/<slug>/',views.open_pdf,name='open-pdf'),
    path('remove-item/<slug>/',views.remove_item,name='remove-item'),
    path('updateProfile/', views.update_address, name='updateProfile'),
]

ecom/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from ecom.settings import MEDIA_ROOT
from signup.views import signup,go_to_setup,accept_otp,login_req 
from django.conf.urls import url
from buyer.views import home_page,addSeller

urlpatterns = [
    path('admin/', admin.site.urls),
    path('buyer/',include('buyer.urls',namespace='buyer')),
    url('signup/', signup, name = 'signup' ),
    url('accounts/login/', login_req, name='login'),
    path('accounts/', include('django.contrib.auth.urls')),
    url('setup-otp/',go_to_setup , name = 'setup-otp' ),
    url('otp/',accept_otp, name = 'accept-otp' ),
    path('',home_page ),
    path('upgrade', addSeller),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=MEDIA_ROOT)

buyer/models.py
from django.db import models
from django.shortcuts import reverse
from django.conf import settings
from signup.models import seller
from signup.formatChecker import ContentTypeRestrictedFileField
# Create your models here.
class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    #category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    slug = models.SlugField(unique=True)
    description = models.TextField()
    #image = models.ImageField(upload_to='images')
    image = ContentTypeRestrictedFileField(upload_to='images',content_types=['image/jpeg','image/jpg','image/png'],max_upload_size=5242880,blank=True, null=True)
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("buyer:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("buyer:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("buyer:remove-from-cart", kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

class sellerItems(models.Model):
    seller = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    item = models.ManyToManyField(Item)
    #quantity = models.IntegerField(default=1)
    def get_seller(self):
        return self.seller

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    items = models.ManyToManyField(OrderItem)
    payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.user.username
    
    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_total_item_price()
        return total


class Payment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    order_id=models.CharField(max_length=100,blank=True)
    razorpay_order_id=models.CharField(max_length=100,blank=True)

    def __str__(self):
        return self.user.username

buyer/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from signup.models import UserProfile
from buyer.models import Item,sellerItems
from signup.models import seller



class addProductForm(forms.ModelForm):
    # Prod_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    # Prod_id = forms.IntegerField(required=True, help_text='Optional.')
    # Prod_desp= forms.CharField(max_length=30, required=False, help_text='Optional.')
    # Price = forms.IntegerField(required=True)

    # Prod_img = forms.ImageField()
    # email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
    # is_seller = forms.BooleanField(initial=True)


    class Meta:
        model = Item
        fields = ('title', 'price',  'slug','description','image')
    #def save():

class addSellerForm(forms.ModelForm):

    class Meta:
        model = seller
        fields = ('pdf',)
        # exclude = ('user',)

class item_to_sellerform(forms.ModelForm):
    class Meta:
        model = sellerItems
        fields = ('seller','item')

class update_user_address(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('address',)

buyer/views.py
from django.shortcuts import render,get_object_or_404,redirect,HttpResponse
from django.db.models import Q
from .models import Item,OrderItem,Order,Payment,sellerItems
from signup.models import UserProfile
from django.views.generic import DetailView
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.mixins import LoginRequiredMixin
from ecom.settings import RZP_API_KEY,RZP_SECRET_KEY,MEDIA_ROOT
import razorpay
from django.contrib.auth import get_user_model, login,logout
from django.views.decorators.csrf import csrf_exempt
from signup.models import seller,Admin
from signup.views import go_to_setup 
from .forms import addProductForm,addSellerForm,item_to_sellerform,update_user_address
import time
from django.http import FileResponse
import os
elaspsed=300
# Create your views here.
User=get_user_model()
def home_page(request):
    user_ = request.user 
    if(request.user.is_anonymous):
        context={
            'items':Item.objects.all()
        }
        return render(request,'buyer_homepage.html',context)
    if(len(seller.objects.filter(user = user_))!=0):
        item_list =[]
        item_list.extend(sellerItems.objects.filter(seller = user_)[0].item.all())
        context={
            'sellerItems':item_list
        }
        return render(request, 'seller_portal.html', context)
    if(is_admin(user_)):
        return redirect('/buyer/admin-home/')
    context={
        'items':Item.objects.all()
    }
    return render(request,'buyer_homepage.html',context)

class ItemDetailView(DetailView):
    model = Item
    template_name = "product_desc.html"

@login_required
def add_to_cart(request, slug):
    profile=UserProfile.objects.filter(user=request.user)[0]
    if profile.secret_string=='':
        return redirect('/setup-otp/')
    elif time.time()-profile.last_otp>=elaspsed:
        return redirect('/otp/')
    user_=request.user
    if((is_admin(user_) or is_seller(user_))):
        return redirect('/buyer/home')
    Buyer=request.user
    item = get_object_or_404(Item, slug=slug)
    order_item= OrderItem.objects.get_or_create(
        item=item,
        user=Buyer,
        ordered=False
    )[0]
    order_qs = Order.objects.filter(user=Buyer, ordered=False)
    #order_qs = Order.objects.filter(ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__slug=item.slug).exists():
            order_item.quantity += 1
            order_item.save()
            messages.info(request, "This item quantity was updated.")
            #return redirect("core:order-summary")
        else:
            order.items.add(order_item)
            messages.info(request, "This item was added to your cart.")
            #return redirect("core:order-summary")
    else:
        order = Order.objects.create(user=Buyer)
        order.items.add(order_item)
        messages.info(request, "This item was added to your cart.")
        #return redirect("core:order-summary")
    return redirect("buyer:product",slug=slug)




@login_required
def remove_from_cart(request, slug):
    
    profile=UserProfile.objects.filter(user=request.user)[0]
    if profile.secret_string=='':
        return redirect('/setup-otp/')
    elif time.time()-profile.last_otp>=elaspsed:
        return redirect('/otp/')
    user_=request.user
    if((is_admin(user_) or is_seller(user_))):
        return redirect('/buyer/home')
    
    item = get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(
        user=request.user,
        ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(
                item=item,
                user=request.user,
                ordered=False
            )[0]
            order.items.remove(order_item)
            order_item.delete()
            messages.info(request, "This item was removed from your cart.")
            #return redirect("core:order-summary")
            return redirect("buyer:product", slug=slug)
        else:
            messages.info(request, "This item was not in your cart")
            return redirect("buyer:product", slug=slug)
    else:
        messages.info(request, "You do not have an active order")
        return redirect("buyer:product", slug=slug)


class OrderSummaryView(LoginRequiredMixin,DetailView):
    def get(self, *args, **kwargs):
        profile=UserProfile.objects.filter(user=self.request.user)[0]
        if profile.secret_string=='':
            return redirect('/setup-otp/')
        elif time.time()-profile.last_otp>=elaspsed:
            return redirect('/otp/')
        user_=self.request.user
        if((is_admin(user_) or is_seller(user_))):
            return redirect('/buyer/home')
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            context = {
                'object': order
            }
            return render(self.request, 'order_summary.html', context)
        except ObjectDoesNotExist:
            messages.warning(self.request, "You do not have an active order")
            return redirect("/buyer/home/")




@login_required
def remove_from_cart(request, slug):
    profile=UserProfile.objects.filter(user=request.user)[0]
    if profile.secret_string=='':
        return redirect('/setup-otp/')
    elif time.time()-profile.last_otp>=elaspsed:
        return redirect('/otp/')
    user_=request.user
    if((is_admin(user_) or is_seller(user_))):
        return redirect('/buyer/home')
    item = get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(
        user=request.user,
        ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(
                item=item,
                user=request.user,
                ordered=False
            )[0]
            order.items.remove(order_item)
            order_item.delete()
            messages.info(request, "This item was removed from your cart.")
            return redirect("buyer:order-summary")
        else:
            messages.info(request, "This item was not in your cart")
            return redirect("buyer:product", slug=slug)
    else:
        messages.info(request, "You do not have an active order")
        return redirect("buyer:product", slug=slug)


@login_required
def remove_single_item_from_cart(request, slug):
    profile=UserProfile.objects.filter(user=request.user)[0]
    if profile.secret_string=='':
        return redirect('/setup-otp/')
    elif time.time()-profile.last_otp>=elaspsed:
        return redirect('/otp/')
    user_=request.user
    if((is_admin(user_) or is_seller(user_))):
        return redirect('/buyer/home')
    item = get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(
        user=request.user,
        ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(
                item=item,
                user=request.user,
                ordered=False
            )[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
            else:
                order.items.remove(order_item)
            messages.info(request, "This item quantity was updated.")
            return redirect("buyer:order-summary")
        else:
            messages.info(request, "This item was not in your cart")
            return redirect("buyer:product", slug=slug)
    else:
        messages.info(request, "You do not have an active order")
        return redirect("buyer:product", slug=slug)

class CheckoutView(LoginRequiredMixin,DetailView):
    def get(self, *args, **kwargs):
        profile=UserProfile.objects.filter(user=self.request.user)[0]
        if profile.secret_string=='':
            return redirect('/setup-otp/')
        elif time.time()-profile.last_otp>=elaspsed:
            return redirect('/otp/')
        user_=self.request.user
        if((is_admin(user_) or is_seller(user_))):
            return redirect('/buyer/home')
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            context = {
                'object': order
            }
            return render(self.request, 'pre_payment.html', context)
        except ObjectDoesNotExist:
            messages.warning(self.request, "You do not have an active order")
            return redirect("/buyer/home/")


@login_required
def pay(request):
    profile=UserProfile.objects.filter(user=request.user)[0]
    if profile.secret_string=='':
        return redirect('/setup-otp/')
    elif time.time()-profile.last_otp>=elaspsed:
        return redirect('/otp/')
    order_amount=0
    user_=request.user
    if((is_admin(user_) or is_seller(user_))):
        return redirect('/buyer/home')
    try:
        order = Order.objects.get(user=request.user, ordered=False)
        order_amount=order.get_total()*100
    except ObjectDoesNotExist:
            messages.warning(request, "You do not have an active order")
            return redirect("/buyer/home/")
    client = razorpay.Client(auth=(RZP_API_KEY,RZP_SECRET_KEY))

    payment_order=client.order.create(dict(amount=order_amount,currency='INR',payment_capture=0))
    payment_order_id=payment_order['id']

    payment=Payment()
    payment.user=request.user
    
    payment.amount=order_amount/100
    payment.order_id=payment_order_id
    payment.save()

    order.payment=payment

    order.save()

    #Order=order(amount=amount,order_id=payment_order_id)
    #Order.save()

    #callback_url='http://'+str(get_current_site(request))+ 'payment_success/'

buyer/templates/failure.html
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
        <title>Failure</title>
    </head>
    
    <body class="text-gray-400 bg-gray-900 body-font">
        <div class="flex flex-col text-center w-full mb-20">
            <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-white">Failure</h1>
           <a href="/buyer/home/"> <p class="lg:w-2/3 mx-auto leading-relaxed text-base">Back to Home</p></a>
          </div>

    </body>
</html>

buyer/templates/order_summary.html
<!DOCTYPE html>
<html lang="en">
<head>
  <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Summary</title>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>
<body class="text-gray-400 bg-gray-900 body-font">

  <div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
  </div>
    <!-- <main> -->
      <div class="container px-5 py-24 mx-auto">
        <div class="flex flex-col text-center w-full mb-20">
          <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-white">Cart</h1>
          <p class="lg:w-2/3 mx-auto leading-relaxed text-base">All items are listed here, change quantity or delete items as needed</p>
        </div>
        <div class="lg:w-2/3 w-full mx-auto overflow-auto">
          <table class="table-auto w-full text-left whitespace-no-wrap">
            <thead>
              <tr>
                <th class="px-4 py-3 title-font tracking-wider font-medium text-white text-sm bg-gray-800 rounded-tl rounded-bl">Number</th>
                <th class="px-4 py-3 title-font tracking-wider font-medium text-white text-sm bg-gray-800">Item Name</th>
                <th class="px-4 py-3 title-font tracking-wider font-medium text-white text-sm bg-gray-800">Price</th>
                <th class="px-4 py-3 title-font tracking-wider font-medium text-white text-sm bg-gray-800">Quantity</th>
               
              </tr>
            </thead>
            
            <tbody>
            {% for order_item in object.items.all %}
              <tr>
                  <th scope="row">{{ forloop.counter }}</th>
                  <td class="px-4 py-3">{{ order_item.item.title }}</td>
                  <td class="px-4 py-3">{{ order_item.item.price }}</td>
                  <td class="px-4 py-3">
                      <a href="{% url 'buyer:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a>
                      {{ order_item.quantity }}
                      <a href="{% url 'buyer:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-2"></i></a>
                  </td>
                  <td class="px-4 py-3">
                  <a style='color: red;' href="{% url 'buyer:remove-from-cart' order_item.item.slug %}">
                      <i class="fas fa-trash float-right"></i>
                  </a>
                  </td>
              </tr>
              {% empty %}
              <tr>
                  <td colspan='4' class="px-4 py-3">Your cart is empty</td>
              </tr>
              <tr>
                  <td class="px-4 py-3" colspan="4">
                  <a class='btn btn-primary float-right' href='/buyer/home/'>Continue shopping</a>
                  </td>
              </tr>
              {% endfor %}
              {% if object.get_total %}
          <tr>
              <td colspan="3"><b>Order Total</b></td>
              <td><b>₹{{ object.get_total }}</b></td>
          </tr>
          
          {% endif %}
          </tbody>
      </table>
      

    </div>
  
  
  <div class="flex pl-4 mt-4 lg:w-2/3 w-full mx-auto">
    <a class="text-blue-400 inline-flex items-center md:mb-2 lg:mb-0" href='/buyer/home/'>Continue shopping
      <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    </a>
    <a href='/buyer/checkout/'><button class="flex ml-auto text-white bg-blue-500 border-0 py-2 px-6 focus:outline-none hover:bg-blue-600 rounded">Checkout</button></a>
  </div>
  </div>
  <!-- </main> -->
</body>
</html>

buyer/templates/payment.html
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
        <title>Confirm Order</title>
    </head>
<body class="text-gray-400 bg-gray-900 body-font">
    <div class="flex flex-col text-center w-full mb-20">
	<h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-white"> Checkout </h1>
	<p>Amount = Rs {{amount}}</p>
    <form action="/buyer/pay/payment-status/" method="post" class="form">
        {% csrf_token %}
        <div class='row'>
	        <button id="rzp-button1" class="text-white bg-blue-500 border-0 py-2 px-6 focus:outline-none hover:bg-blue-600 rounded">Pay</button>
        </div>
    </form>
</div>
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
var options = {
    "key": "{{api_key}}", 
    "name": "FCS",
    "description": "Transaction",
    "image": "https://logos-world.net/wp-content/uploads/2020/10/Target-Logo.png",
    "order_id": "{{order_id}}",
    "callback_url":"{{callback_url}}" ,
    "redirect":false,
    "prefill": {
        "name": "John Doe",
        "email": "John@example.com",
        "contact": "9999999999"
    },
    "notes": {
        "address": "Razorpay Corporate Office"
    },
    "theme": {
        "color": "#3399cc"
    }
};
var rzp1 = new Razorpay(options);

document.getElementById('rzp-button1').onclick = function(e){
    rzp1.open();
    e.preventDefault();
}
</script>
</body>
</html>

buyer/templates/seller_portal.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <title>Document</title>
</head>
<body class="text-gray-400 bg-gray-900 body-font">
    <header class="text-gray-400 bg-gray-900 body-font">
        <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
          <a class="flex title-font font-medium items-center text-white-900 mb-4 md:mb-0">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-blue-500 rounded-full" viewBox="0 0 24 24">
              <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
            </svg>
            <span class="ml-3 text-xl">E-Commerce (Seller) </span>
          </a>
          <nav class="md:mr-auto md:ml-4 md:py-1 md:pl-4 md:border-l md:border-gray-400	flex flex-wrap items-center text-base justify-center">
          </nav>
          <form method="post" action="/buyer/logout/">
            {% csrf_token %}
          <button class="flex ml-auto text-white bg-blue-500 border-0 py-2 px-6 focus:outline-none hover:bg-blue-600 rounded"  >Logout
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
              <path d="M5 12h14M12 5l7 7-7 7"></path>
            </svg>
          </button>
        </form>
        </div>
     </header>
     
      <section class="text-white bg-gray-900 body-font">
        <div class="container px-5 py-24 mx-auto">
          <div class="flex flex-col text-center w-full mb-20">
            <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-white">Seller Portal</h1>
            <p class="lg:w-2/3 mx-auto leading-relaxed text-base"></p>
            <div class="flex pl-4 mt-4 lg:w-1/10 mx-auto">
                <button onclick="location.href='{% url 'buyer:addProd' %}'" class="flex ml-auto text-white bg-blue-500 border-0 py-2 px-6 focus:outline-none hover:bg-blue-600 rounded">Add New Product</button>
              </div>
          </div>
        </div>
          <div class="flex flex-col text-center -m-2">
            <div class="p-12 md:w-1/2 flex flex-col items-start">
                <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-white">Listed Products</h1>
            <table class="table-auto w-full text-center whitespace-no-wrap">
              <thead>
                <tr>
                  <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Product Name</th>
                  <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Product Price</th>
                  <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Description</th>
                  <th class="w-10 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tr rounded-br"></th>
                </tr>
              </thead>
              <tbody>
                {% for item in sellerItems %}
                <tr>

                  <td class="px-4 py-3">{{item.title}}</td>
                  <td class="px-4 py-3">{{item.price}}</td>
                  <td class="px-4 py-3 text-lg text-gray-400">{{item.description}}</td>
                  <td class="w-10 text-center">
                    
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            </div>
            

            
          <!-- <div class="flex pl-4 mt-4 lg:w-1/5 mx-auto">
            <button class="flex ml-auto text-white bg-red-500 border-0 py-2 px-6 focus:outline-none hover:bg-red-600 rounded">Remove</button>
          </div>
          <div class="flex pl-4 mt-4 lg:w-1/5 mx-auto">
            <button class="flex ml-auto text-white bg-blue-500 border-0 py-2 px-6 focus:outline-none hover:bg-blue-600 rounded">Accept</button>
          </div>
          <div class="flex pl-4 mt-4 lg:w-1/10 mx-auto">
            <button class="flex ml-auto text-white bg-red-500 border-0 py-2 px-6 focus:outline-none hover:bg-red-600 rounded">Reject</button>
          </div> -->
        </div>
        </div>
      </section>
      
</body>
</html>

buyer/templates/success.html
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
        <title>Success</title>
    </head>
    
    <body class="text-gray-400 bg-gray-900 body-font">
        <div class="flex flex-col text-center w-full mb-20">
            <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-white">Succcess</h1>
           <a href="/buyer/home/"> <p class="lg:w-2/3 mx-auto leading-relaxed text-base">Back to Home</p></a>
          </div>

    </body>
</html>